// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfbncsvvxkktecxiktkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmYm5jc3Z2eGtrdGVjeGlrdGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzExMTEsImV4cCI6MjA2MjkwNzExMX0.IfxCvrrBnW3LFjyzh7iFFEHKBD14ixKP467MoOMWqLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);